### ISSUE TITLE
Styling problems

### ISSUE THREAD

**Issue by AndreaFerraresi** [openwisp/ansible-openwisp2-imagegenerator#12]
Hey guys, 
Just a couple of styling/best practices issues. 
normally you want to use apt only if the platform is ubuntu and or debian so i would recommend to put a when condition for that.

as in `when ansible_distribution==Debian or ansible_distribution==Ubuntu`

Besides that you normally do not specify become_method and become_user on each task, is normally done in the generic playbook.

Normally you do not want to enforce to use sudo in case the user is running in a fakeroot environment or similia. 

Just my two cents. Don't really have time to send you a pull requests ATM.

**Comment by nemesifier** [comment]
Hi @AndreaFerraresi! This playbook only supports debian and ubuntu systems, so `apt` is good enough. Unfortunately, we can't run the playbooks using this role to run as root with `become` because compiling OpenWRT/LEDE with root would result in failure because it is not allowed. Therefore we must run playbooks using this role with a normal user which has sudo privileges and become root when necessary, if at all (the parts of the role needing root privileges may be skipped if already performed in the past).
I hope it's clear! If you have more suggestions on how to improve things further let us know :-)

Thanks 👍
