### ISSUE TITLE
[release] Update role on ansible galaxy

### ISSUE THREAD

**Issue by mikysal78** [openwisp/ansible-openwisp2-imagegenerator#29]
The repo on [Galaxy](https://galaxy.ansible.com/openwisp/openwisp2-imagegenerator) when will it be updated?
Last Import is 3 years ago

**Comment by nemesifier** [comment]
Hi @mikysal78, sure I will issue a new release once the new version of [openwisp-firmware-upgrader](https://github.com/openwisp/openwisp-firmware-upgrader) is ready (mainly https://github.com/openwisp/openwisp-firmware-upgrader/pull/128), because the master branch has some features to upload the firmware which work only on that version of fw-upgrader.

**Comment by nemesifier** [comment]
Let's leave this open as a reminder.

**Comment by nemesifier** [comment]
Done!
