### ISSUE TITLE
[Feature] Please support OpenWrt 21.02

### ISSUE THREAD

**Issue by imp1sh** [openwisp/ansible-openwisp2-imagegenerator#30]
Hi,

please support OpenWrt 21.02.
I installed the ansible role and changed the variable to:
`
openwisp2fw_source_version: openwrt-21.02
`
Compilation seems to fail to due this change.
Can you please support the most recent version of Openwrt.

**Comment by nemesifier** [comment]
I had the same issue last time I tried. I am not sure when I'll be able to find time to add support for OpenWrt 21.02 in this role. I hope sooner rather than later. Anway, patchs are welcome.

**Comment by imp1sh** [comment]
Well the main problem I guess is that the .config file needs adjustment. Maybe I will have a look into it if I find some time, cannot make any promises here.

**Comment by nemesifier** [comment]
I have been able to generate openwrt 22 based firmwares with this role recently so this issue is invalid.
If anyone is having issues and can replicate the issues consistently: please open a detailed bug report and I recommend looking for a solution and send a patch. I don't have time to solve other people's issues on this particular repo because it's complex and time consuming, I have too much unpaid burden already and can't take on more unpaid work.
